#!/usr/bin/env python3
"""Build CoreDNS sinkhole snippets from domain lists.

Reads blocklists/domains-{porn,malware,social}.txt and writes
blocklists/block-{porn,malware,social}.conf — a stock-plugin `template`
that answers BLOCK_IP for each apex domain AND all its subdomains.
BLOCK_IP is the VPN server IP serving the Hebrew block page
(blockpage/server.py), so users see an explanation instead of a bare
connection failure. Override: FILTERVPN_BLOCK_IP=10.100.0.1
Run:  python3 gen-block-conf.py   (also called by install/update scripts)
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
BL = os.path.join(HERE, "blocklists")
GROUPS = ("porn", "malware", "social", "social-strict")
BLOCK_IP = os.environ.get("FILTERVPN_BLOCK_IP", "10.100.0.1")


def load(fname):
    domains = []
    with open(os.path.join(BL, fname)) as f:
        for line in f:
            line = line.strip().lower()
            if line and not line.startswith("#"):
                domains.append(line)
    return sorted(set(domains))


def main():
    for group in GROUPS:
        domains = load(f"domains-{group}.txt")
        if domains:
            alt = "|".join(re.escape(d) for d in domains)
            match = f"^(.*\\.)?({alt})\\.$"
            note = f"{len(domains)} base domains"
        else:
            match = "^$"  # matches nothing; group currently empty
            note = "empty list (matches nothing)"
        conf = (
            f"# AUTO-GENERATED by gen-block-conf.py from domains-{group}.txt — do not edit.\n"
            f"# Sends apex + all subdomains to {BLOCK_IP} (Hebrew block page) ({note}).\n"
            f"template ANY ANY . {{\n"
            f"  match {match}\n"
            f'  answer "{{{{ .Name }}}} 60 IN A {BLOCK_IP}"\n'
            f"  fallthrough\n"
            f"}}\n"
        )
        # sanity: regex must compile (Python re is close enough to RE2 for this syntax)
        re.compile(match)
        out = os.path.join(BL, f"block-{group}.conf")
        with open(out, "w") as f:
            f.write(conf)
        print(f"wrote {out} ({note})")


if __name__ == "__main__":
    main()
